# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('description', models.TextField(default='They are not honest')),
                ('availability', models.TextField(default='daily')),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
