# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndApp', '0002_auto_20170530_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='names',
            field=models.TextField(max_length=20),
        ),
    ]
